name: Build and Publish on Version Change

on:
  push:
    paths:
      - 'package.json'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org/'
    - run: npm ci
    - run: npm run build
    - name: Check Version Change
      run: |
        git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '^package.json' && \
        node -e "const p = require('./package.json'); console.log('New version:', p.version)" || exit 0
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}